/*
 * Generated by gdbus-codegen 2.33.12. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifndef __INTROSPECTIONSERVICE_H__
#define __INTROSPECTIONSERVICE_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for com.canonical.Autopilot.Introspection */

#define TYPE_AUTOPILOT_INTROSPECTION (autopilot_introspection_get_type ())
#define AUTOPILOT_INTROSPECTION(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_AUTOPILOT_INTROSPECTION, AutopilotIntrospection))
#define IS_AUTOPILOT_INTROSPECTION(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_AUTOPILOT_INTROSPECTION))
#define AUTOPILOT_INTROSPECTION_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), TYPE_AUTOPILOT_INTROSPECTION, AutopilotIntrospectionIface))

struct _AutopilotIntrospection;
typedef struct _AutopilotIntrospection AutopilotIntrospection;
typedef struct _AutopilotIntrospectionIface AutopilotIntrospectionIface;

struct _AutopilotIntrospectionIface
{
  GTypeInterface parent_iface;

  gboolean (*handle_get_state) (
    AutopilotIntrospection *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_piece);

};

GType autopilot_introspection_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *autopilot_introspection_interface_info (void);
guint autopilot_introspection_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void autopilot_introspection_complete_get_state (
    AutopilotIntrospection *object,
    GDBusMethodInvocation *invocation,
    GVariant *state);



/* D-Bus method calls: */
void autopilot_introspection_call_get_state (
    AutopilotIntrospection *proxy,
    const gchar *arg_piece,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean autopilot_introspection_call_get_state_finish (
    AutopilotIntrospection *proxy,
    GVariant **out_state,
    GAsyncResult *res,
    GError **error);

gboolean autopilot_introspection_call_get_state_sync (
    AutopilotIntrospection *proxy,
    const gchar *arg_piece,
    GVariant **out_state,
    GCancellable *cancellable,
    GError **error);



/* ---- */

#define TYPE_AUTOPILOT_INTROSPECTION_PROXY (autopilot_introspection_proxy_get_type ())
#define AUTOPILOT_INTROSPECTION_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_AUTOPILOT_INTROSPECTION_PROXY, AutopilotIntrospectionProxy))
#define AUTOPILOT_INTROSPECTION_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_AUTOPILOT_INTROSPECTION_PROXY, AutopilotIntrospectionProxyClass))
#define AUTOPILOT_INTROSPECTION_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_AUTOPILOT_INTROSPECTION_PROXY, AutopilotIntrospectionProxyClass))
#define IS_AUTOPILOT_INTROSPECTION_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_AUTOPILOT_INTROSPECTION_PROXY))
#define IS_AUTOPILOT_INTROSPECTION_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_AUTOPILOT_INTROSPECTION_PROXY))

typedef struct _AutopilotIntrospectionProxy AutopilotIntrospectionProxy;
typedef struct _AutopilotIntrospectionProxyClass AutopilotIntrospectionProxyClass;
typedef struct _AutopilotIntrospectionProxyPrivate AutopilotIntrospectionProxyPrivate;

struct _AutopilotIntrospectionProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  AutopilotIntrospectionProxyPrivate *priv;
};

struct _AutopilotIntrospectionProxyClass
{
  GDBusProxyClass parent_class;
};

GType autopilot_introspection_proxy_get_type (void) G_GNUC_CONST;

void autopilot_introspection_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
AutopilotIntrospection *autopilot_introspection_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
AutopilotIntrospection *autopilot_introspection_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void autopilot_introspection_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
AutopilotIntrospection *autopilot_introspection_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
AutopilotIntrospection *autopilot_introspection_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define TYPE_AUTOPILOT_INTROSPECTION_SKELETON (autopilot_introspection_skeleton_get_type ())
#define AUTOPILOT_INTROSPECTION_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_AUTOPILOT_INTROSPECTION_SKELETON, AutopilotIntrospectionSkeleton))
#define AUTOPILOT_INTROSPECTION_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_AUTOPILOT_INTROSPECTION_SKELETON, AutopilotIntrospectionSkeletonClass))
#define AUTOPILOT_INTROSPECTION_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_AUTOPILOT_INTROSPECTION_SKELETON, AutopilotIntrospectionSkeletonClass))
#define IS_AUTOPILOT_INTROSPECTION_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_AUTOPILOT_INTROSPECTION_SKELETON))
#define IS_AUTOPILOT_INTROSPECTION_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_AUTOPILOT_INTROSPECTION_SKELETON))

typedef struct _AutopilotIntrospectionSkeleton AutopilotIntrospectionSkeleton;
typedef struct _AutopilotIntrospectionSkeletonClass AutopilotIntrospectionSkeletonClass;
typedef struct _AutopilotIntrospectionSkeletonPrivate AutopilotIntrospectionSkeletonPrivate;

struct _AutopilotIntrospectionSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  AutopilotIntrospectionSkeletonPrivate *priv;
};

struct _AutopilotIntrospectionSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType autopilot_introspection_skeleton_get_type (void) G_GNUC_CONST;

AutopilotIntrospection *autopilot_introspection_skeleton_new (void);


G_END_DECLS

#endif /* __INTROSPECTIONSERVICE_H__ */
